name: Deploy GeoPortal to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Construir sitio
        run: npm run build

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v4